# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#title: mvdbos.github.io
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

# Build settings
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/mvdbos" }
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/matthijsvdbos/" }
    - { platform: keybase,  user_url: "https://keybase.io/mvdbos" }
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .idea/

